backend:
  name: github
  repo: nathanhall762/tulsacustomwebsites # Path to your GitHub repository
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
site_url: https://tulsacustomwebsites.com
display_url: https://tulsacustomwebsites.com
logo_url: 'src/media/Tulsa-Custom-Websites-1.webp'
media_folder: 'src/media' # Location where files will be stored in the repo
public_folder: 'src/media' # The src attribute for uploaded media
collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/pages
    label: 'Pages' # Used in the UI
    label_singular: 'Page'
    folder: 'src/content/pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new pages
    fields:
      - {
          label: 'Page Title',
          name: 'title',
          widget: 'string',
          default: 'Untitled Page',
        }
      - {
          label: 'URL Slug',
          name: 'slug',
          widget: 'string',
          default: 'untitled-page',
        }
      - {
          label: 'Parent Route',
          name: 'parent route',
          widget: 'string',
          default: '/',
        }
      - {
          label: 'Content',
          name: 'content',
          widget: 'list',
          types:
            [
              {
                label: 'Hero',
                name: 'hero',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Type',
                      name: 'type',
                      widget: 'string',
                      default: 'hero',
                    },
                    {
                      label: 'Value',
                      name: 'value',
                      widget: 'object',
                      fields:
                        [
                          {
                            label: 'Heading',
                            name: 'heading',
                            widget: 'string',
                            default: 'Welcome to Our Website',
                          },
                          {
                            label: 'Subheading',
                            name: 'subheading',
                            widget: 'string',
                            default: 'We offer the best services in town.',
                          },
                          {
                            label: 'Images',
                            name: 'images',
                            widget: 'list',
                            field:
                              {
                                label: 'Image',
                                name: 'image',
                                widget: 'image',
                                default: 'https://placehold.co/1920x1080',
                              },
                          },
                          {
                            label: 'Call to Action Text',
                            name: 'call_to_action_text',
                            widget: 'string',
                            required: false,
                            default: 'Learn More',
                          },
                          {
                            label: 'Call to Action Link',
                            name: 'call_to_action_link',
                            widget: 'string',
                            required: false,
                            default: '#',
                          },
                        ],
                    },
                  ],
              },
              {
                label: 'Sidekick',
                name: 'sidekick',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Type',
                      name: 'type',
                      widget: 'string',
                      default: 'sidekick',
                    },
                    {
                      label: 'Value',
                      name: 'value',
                      widget: 'object',
                      fields:
                        [
                          {
                            label: 'Heading',
                            name: 'heading',
                            widget: 'string',
                            default: 'Our Sidekick',
                          },
                          {
                            label: 'Subheading',
                            name: 'subheading',
                            widget: 'string',
                            default: 'Helping you achieve more.',
                          },
                          {
                            label: 'Image',
                            name: 'image',
                            widget: 'image',
                            default: 'https://placehold.co/1440x550',
                          },
                          {
                            label: 'Call to Action Text',
                            name: 'call_to_action_text',
                            widget: 'string',
                            required: false,
                            default: 'Find Out More',
                          },
                          {
                            label: 'Call to Action Link',
                            name: 'call_to_action_link',
                            widget: 'string',
                            required: false,
                            default: '#',
                          },
                        ],
                    },
                  ],
              },
              {
                label: 'Accordion',
                name: 'accordion',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Type',
                      name: 'type',
                      widget: 'string',
                      default: 'accordion',
                    },
                    {
                      label: 'Value',
                      name: 'value',
                      widget: 'object',
                      fields:
                        [
                          {
                            label: 'Heading',
                            name: 'heading',
                            widget: 'string',
                            default: 'Frequently Asked Questions',
                          },
                          {
                            label: 'Questions and Answers',
                            name: 'question_and_answer',
                            widget: 'list',
                            fields:
                              [
                                {
                                  label: 'Question',
                                  name: 'question',
                                  widget: 'string',
                                  default: 'What is this?',
                                },
                                {
                                  label: 'Answer',
                                  name: 'answer',
                                  widget: 'text',
                                  default: 'This is an answer.',
                                },
                              ],
                          },
                        ],
                    },
                  ],
              },
            ],
        }
      - {
          label: 'SEO Description',
          name: 'seo_description',
          widget: 'text',
          required: false,
          default: 'This is a page description for SEO purposes.',
        }
