backend:
  name: github
  repo: nathanhall762/tulsacustomwebsites # Path to your GitHub repository
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
site_url: https://tulsacustomwebsites.com
display_url: https://tulsacustomwebsites.com
logo_url: 'src/media/Tulsa-Custom-Websites-1.webp'
media_folder: 'src/media' # Location where files will be stored in the repo
public_folder: 'src/media' # The src attribute for uploaded media
collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/pages
    label: 'Pages' # Used in the UI
    label_singular: 'Page'
    folder: 'public/content/pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new pages

    fields:
      - { label: 'Page Title', name: 'title', widget: 'string' }
      - { label: 'URL Slug', name: 'slug', widget: 'string' }
      - { label: 'Parent Route', name: 'parent route', widget: 'datetime' }
      - {
          label: 'Content',
          name: 'content',
          widget: 'list',
          types:
            [
              {
                label: 'Carousel',
                name: 'carousel',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Images',
                      name: 'images',
                      widget: 'list',
                      field: { label: 'Image', name: 'image', widget: 'image' },
                    },
                    {
                      label: 'Autoplay',
                      name: 'autoplay',
                      widget: 'boolean',
                      default: true,
                    },
                  ],
              },
              {
                label: 'Accordion',
                name: 'accordion',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Items',
                      name: 'items',
                      widget: 'list',
                      fields:
                        [
                          { label: 'Title', name: 'title', widget: 'string' },
                          {
                            label: 'Content',
                            name: 'content',
                            widget: 'markdown',
                          },
                        ],
                    },
                  ],
              },
            ],
        }
      - {
          label: 'SEO Description',
          name: 'seo_description',
          widget: 'text',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
