// @ts-nocheck
import { EntityCollection } from "@firecms/cloud";

export const PagesCollection:EntityCollection = {
	id: 'pages',
	name: 'Pages',
	singularName: 'Page',
	path: 'pages',
	description: 'List of website pages that can be edited here',
	editable: true,
	icon: 'insert_drive_file',
	initialFilter: null,
	initialSort: [
		'title',
		'asc',
	],
	properties: {
		title: {
			name: 'Page Title',
			validation: {
				required: true,
			},
			columnWidth: 272.1999816894531,
			dataType: 'string',
		},
		slug: {
			dataType: 'string',
			validation: {
				matches: {},
				matchesMessage: 'Must be lowercase, alphanumeric, and hyphenated',
				unique: true,
				required: true,
			},
			name: 'URL Slug',
			hideFromCollection: false,
		},
		content: {
			name: 'Content',
			hideFromCollection: true,
			description: 'Select Components to Appear on Webpage, in Order',
			dataType: 'array',
			propertyConfig: 'block',
			oneOf: {
				propertiesOrder: [
					'sidekick_section',
					'welcome_message_section',
					'hero_section',
					'info_card_list',
					'bullet_stats_card',
					'tab_list_cards',
					'text_image_card',
					'accordion',
				],
				properties: {
					info_card_list: {
						properties: {
							heading: {
								defaultValue: 'Heading Goes Here',
								dataType: 'string',
								markdown: true,
								editable: true,
								name: 'Heading',
								propertyConfig: 'markdown',
							},
							card: {
								of: {
									dataType: 'map',
									keyValue: false,
									editable: true,
									propertyConfig: 'group',
									name: '',
									properties: {
										alt_image_text: {
											name: 'Alt Image Text',
											propertyConfig: 'text_field',
											editable: true,
											dataType: 'string',
										},
										heading: {
											editable: true,
											markdown: true,
											name: 'Heading',
											defaultValue: 'Heading Goes Here',
											propertyConfig: 'markdown',
											dataType: 'string',
										},
										body_text: {
											markdown: true,
											name: 'Body Text',
											editable: true,
											propertyConfig: 'markdown',
											dataType: 'string',
											defaultValue: 'Body text goes here. Remember, it is a card, so space is relatively limited.',
										},
										image: {
											propertyConfig: 'multi_file_upload',
											of: {
												storage: {
													acceptedFiles: [
														'image/*',
														'video/*',
													],
													storeUrl: true,
													storagePath: '/',
												},
												dataType: 'string',
											},
											dataType: 'array',
											name: 'Image',
											editable: true,
										},
									},
									propertiesOrder: [
										'heading',
										'body_text',
										'image',
										'alt_image_text',
									],
								},
								editable: true,
								dataType: 'array',
								propertyConfig: 'repeat',
								name: 'Card',
							},
						},
						propertiesOrder: [
							'heading',
							'card',
						],
						keyValue: false,
						editable: true,
						name: 'Info Card List',
						dataType: 'map',
						propertyConfig: 'group',
					},
					accordion: {
						editable: true,
						properties: {
							question_and_answer: {
								editable: true,
								dataType: 'array',
								propertyConfig: 'repeat',
								name: 'Question and Answer',
								of: {
									propertiesOrder: [
										'question',
										'answer',
									],
									keyValue: false,
									editable: true,
									dataType: 'map',
									name: '',
									propertyConfig: 'group',
									properties: {
										question: {
											defaultValue: 'How many roads must a man walk down, before they call him a man?',
											editable: true,
											propertyConfig: 'markdown',
											markdown: true,
											name: 'Question',
											dataType: 'string',
										},
										answer: {
											dataType: 'string',
											propertyConfig: 'markdown',
											editable: true,
											name: 'Answer',
											defaultValue: 'I would walk 500 miles and I would walk 500 more.',
											markdown: true,
										},
									},
								},
							},
							heading: {
								name: 'Heading',
								markdown: true,
								editable: true,
								propertyConfig: 'markdown',
								defaultValue: 'Heading Goes Here',
								dataType: 'string',
							},
						},
						keyValue: false,
						propertyConfig: 'group',
						dataType: 'map',
						propertiesOrder: [
							'heading',
							'question_and_answer',
						],
						name: 'Accordion',
					},
					text_image_card: {
						properties: {
							reversed: {
								editable: true,
								defaultValue: false,
								dataType: 'boolean',
								propertyConfig: 'switch',
								name: 'Reversed',
							},
							image_alt_text: {
								dataType: 'string',
								name: 'Image Alt Text',
								propertyConfig: 'text_field',
								editable: true,
							},
							link_url: {
								propertyConfig: 'url',
								name: 'Link Url',
								url: true,
								dataType: 'string',
								editable: true,
							},
							link_text: {
								defaultValue: 'Click Here to Find Out More!',
								name: 'Link Text',
								dataType: 'string',
								editable: true,
								markdown: true,
								propertyConfig: 'markdown',
							},
							heading: {
								markdown: true,
								name: 'Heading',
								propertyConfig: 'markdown',
								defaultValue: 'Heading Goes Here',
								dataType: 'string',
								editable: true,
							},
							image: {
								editable: true,
								dataType: 'string',
								name: 'Image',
								storage: {
									storeUrl: true,
									storagePath: '/',
									acceptedFiles: [
										'image/*',
									],
								},
								propertyConfig: 'file_upload',
							},
							body_text: {
								markdown: true,
								propertyConfig: 'markdown',
								dataType: 'string',
								editable: true,
								name: 'Body Text',
								defaultValue: 'Body text goes here. This can be quite a bit of text, as needed.',
							},
						},
						name: 'Text Image Card',
						editable: true,
						propertiesOrder: [
							'heading',
							'image',
							'image_alt_text',
							'body_text',
							'link_url',
							'link_text',
							'reversed',
						],
						dataType: 'map',
						propertyConfig: 'group',
						keyValue: false,
					},
					welcome_message_section: {
						keyValue: false,
						editable: true,
						propertyConfig: 'group',
						propertiesOrder: [
							'heading',
							'body_text',
							'link_text',
							'link_url',
						],
						properties: {
							link_url: {
								editable: true,
								name: 'Link Url',
								propertyConfig: 'url',
								dataType: 'string',
								url: true,
							},
							link_text: {
								markdown: true,
								propertyConfig: 'markdown',
								dataType: 'string',
								name: 'Link Text',
								editable: true,
								defaultValue: 'Click Here to Find Out More!',
							},
							heading: {
								defaultValue: 'Heading Goes Here',
								dataType: 'string',
								propertyConfig: 'markdown',
								markdown: true,
								name: 'Heading',
								editable: true,
							},
							body_text: {
								defaultValue: 'Body text goes here. This is the place where the user is introduced to what the page is all about. Keep it relatively short and very descriptive.',
								description: 'Short paragraph describing the page. This is the first long section of text a visitor sees when navigating to this page, so be like a museum tour guide who has just taken their group to a different wing of the museum and briefly convey what this page is all about.',
								editable: true,
								markdown: true,
								name: 'Body Text',
								propertyConfig: 'markdown',
								dataType: 'string',
							},
						},
						dataType: 'map',
						name: 'Welcome Message Section',
					},
					url: {
						propertyConfig: 'url',
						dataType: 'string',
						url: true,
						name: 'url',
						editable: true,
					},
					sidekick_section: {
						name: 'Sidekick Section',
						editable: true,
						dataType: 'map',
						keyValue: false,
						properties: {
							call_to_action_text: {
								propertyConfig: 'markdown',
								markdown: true,
								editable: true,
								defaultValue: 'Click Here to Find Out More!',
								dataType: 'string',
								name: 'Call to Action Text',
							},
							image: {
								name: 'Image',
								editable: true,
								dataType: 'array',
								propertyConfig: 'multi_file_upload',
								of: {
									storage: {
										acceptedFiles: [
											'image/*',
											'video/*',
										],
										storagePath: '/',
										storeUrl: true,
									},
									dataType: 'string',
								},
							},
							call_to_action_link: {
								name: 'Call to Action Link',
								dataType: 'string',
								editable: true,
								propertyConfig: 'url',
								url: true,
							},
							heading: {
								markdown: true,
								dataType: 'string',
								name: 'Heading',
								editable: true,
								defaultValue: 'Heading Goes Here',
								propertyConfig: 'markdown',
							},
							subheading: {
								name: 'Subheading',
								markdown: true,
								editable: true,
								defaultValue: 'Subheading Goes Here',
								dataType: 'string',
								propertyConfig: 'markdown',
							},
						},
						propertiesOrder: [
							'heading',
							'subheading',
							'image',
							'call_to_action_text',
							'call_to_action_link',
						],
						propertyConfig: 'group',
					},
					tab_list_cards: {
						editable: true,
						propertyConfig: 'group',
						propertiesOrder: [
							'heading',
							'default_card',
							'cards',
						],
						dataType: 'map',
						keyValue: false,
						name: 'Tab List Cards',
						properties: {
							default_card: {
								keyValue: false,
								editable: true,
								propertiesOrder: [
									'heading',
									'body_text',
									'image',
									'alt_image_text',
									'call_to_action_text',
									'call_to_action_link',
								],
								name: 'Default Card',
								dataType: 'map',
								properties: {
									body_text: {
										propertyConfig: 'markdown',
										defaultValue: 'Body text goes here. This is the copy users will see before selecting any of the category tabs.',
										dataType: 'string',
										markdown: true,
										name: 'Body Text',
										editable: true,
									},
									call_to_action_text: {
										defaultValue: 'Click Here to Find Out More!',
										dataType: 'string',
										editable: true,
										name: 'Call to Action Text',
										markdown: true,
										propertyConfig: 'markdown',
									},
									heading: {
										markdown: true,
										propertyConfig: 'markdown',
										editable: true,
										defaultValue: 'Heading Goes Here',
										dataType: 'string',
										name: 'Heading',
									},
									alt_image_text: {
										name: 'Alt Image Text',
										editable: true,
										propertyConfig: 'text_field',
										dataType: 'string',
									},
									call_to_action_link: {
										propertyConfig: 'url',
										dataType: 'string',
										editable: true,
										name: 'Call To Action Link',
										url: true,
									},
									image: {
										name: 'image',
										storage: {
											storeUrl: true,
											storagePath: '/',
											acceptedFiles: [
												'image/*',
											],
										},
										dataType: 'string',
										propertyConfig: 'file_upload',
										editable: true,
									},
								},
								propertyConfig: 'group',
							},
							heading: {
								propertyConfig: 'markdown',
								editable: true,
								name: 'Heading',
								dataType: 'string',
								defaultValue: 'Heading Goes Here',
								markdown: true,
							},
							cards: {
								editable: true,
								dataType: 'array',
								of: {
									keyValue: false,
									name: '',
									properties: {
										alt_image_text: {
											dataType: 'string',
											editable: true,
											propertyConfig: 'text_field',
											name: 'Alt Image Text',
										},
										body_text: {
											propertyConfig: 'markdown',
											name: 'Body Text',
											dataType: 'string',
											defaultValue: 'Body text for this card goes here.',
											editable: true,
											markdown: true,
										},
										call_to_action_link: {
											name: 'Call To Action Link',
											editable: true,
											propertyConfig: 'url',
											url: true,
											dataType: 'string',
										},
										heading: {
											dataType: 'string',
											editable: true,
											markdown: true,
											name: 'Heading',
											defaultValue: 'Heading Goes Here',
											propertyConfig: 'markdown',
										},
										call_to_action_text: {
											dataType: 'string',
											defaultValue: 'Click Here to Find Out More',
											markdown: true,
											name: 'Call to Action Text',
											editable: true,
											propertyConfig: 'markdown',
										},
										image: {
											dataType: 'string',
											propertyConfig: 'file_upload',
											editable: true,
											name: 'image',
											storage: {
												storagePath: '/',
												storeUrl: true,
												acceptedFiles: [
													'image/*',
												],
											},
										},
									},
									editable: true,
									propertyConfig: 'group',
									propertiesOrder: [
										'heading',
										'body_text',
										'image',
										'alt_image_text',
										'call_to_action_text',
										'call_to_action_link',
									],
									dataType: 'map',
								},
								name: 'Cards',
								propertyConfig: 'repeat',
							},
						},
					},
					text: {
						name: 'Text',
						dataType: 'string',
						markdown: true,
						propertyConfig: 'markdown',
						defaultValue: 'Click here to find out more!',
						editable: true,
					},
					hero_section: {
						properties: {
							header: {
								propertyConfig: 'markdown',
								markdown: true,
								editable: true,
								name: 'Heading',
								defaultValue: 'Hero Heading Goes Here',
								dataType: 'string',
							},
							heading: {
								defaultValue: 'Heading Goes Here',
								editable: true,
								propertyConfig: 'markdown',
								markdown: true,
								dataType: 'string',
								name: 'Heading',
							},
							call_to_action_url: {
								url: true,
								name: 'Call to Action Url',
								editable: true,
								propertyConfig: 'url',
								dataType: 'string',
							},
							call_to_action_text: {
								propertyConfig: 'markdown',
								markdown: true,
								name: 'Call to Action Text',
								editable: true,
								defaultValue: 'Click Here to Find Out More!',
								dataType: 'string',
							},
							subheading: {
								propertyConfig: 'markdown',
								markdown: true,
								name: 'Subheading',
								defaultValue: 'Subheading Goes Here',
								dataType: 'string',
								editable: true,
							},
							image: {
								propertyConfig: 'multi_file_upload',
								name: 'Image',
								of: {
									dataType: 'string',
									storage: {
										acceptedFiles: [
											'image/*',
											'video/*',
										],
										storagePath: '/',
										storeUrl: true,
									},
								},
								editable: true,
								dataType: 'array',
								validation: {
									required: false,
								},
							},
							call_to_action: {
								propertiesOrder: [
									'text',
									'url',
								],
								editable: true,
								keyValue: false,
								name: 'Call to Action',
								properties: {
									url: {
										propertyConfig: 'url',
										editable: true,
										dataType: 'string',
										name: 'url',
										url: true,
									},
									text: {
										dataType: 'string',
										editable: true,
										markdown: true,
										name: 'Text',
										propertyConfig: 'markdown',
									},
								},
								propertyConfig: 'group',
								dataType: 'map',
							},
							images: {
								name: 'Images',
								editable: true,
								propertyConfig: 'multi_file_upload',
								dataType: 'array',
								of: {
									dataType: 'string',
									storage: {
										storeUrl: true,
										acceptedFiles: [
											'image/*',
											'video/*',
										],
										storagePath: '/',
									},
								},
							},
							call_to_action_link: {
								propertyConfig: 'url',
								dataType: 'string',
								name: 'Call to Action Link',
								editable: true,
								url: true,
							},
						},
						name: 'Hero Section',
						keyValue: false,
						oneOf: {
							properties: {
								heading: {
									propertyConfig: 'markdown',
									defaultValue: 'Heading Goes Here',
									editable: true,
									markdown: true,
									name: 'Heading',
									dataType: 'string',
								},
								call_to_action_text: {
									name: 'Call to Action Text',
									dataType: 'string',
									markdown: true,
									propertyConfig: 'markdown',
									editable: true,
									defaultValue: 'Click Here to Find Out More!',
								},
								subheading: {
									dataType: 'string',
									name: 'Subheading',
									defaultValue: 'Subheading Goes Here',
									markdown: true,
									propertyConfig: 'markdown',
									editable: true,
								},
								call_to_action_link: {
									name: 'Call To Action Link',
									propertyConfig: 'markdown',
									editable: true,
									markdown: true,
									dataType: 'string',
								},
								images: {
									dataType: 'array',
									propertyConfig: 'multi_file_upload',
									name: 'Images',
									of: {
										storage: {
											storeUrl: true,
											acceptedFiles: [
												'image/*',
												'video/*',
											],
											storagePath: '/',
										},
										dataType: 'string',
									},
									editable: true,
								},
							},
							propertiesOrder: [
								'heading',
								'subheading',
								'images',
								'call_to_action_text',
								'call_to_action_link',
							],
						},
						editable: true,
						dataType: 'map',
						propertyConfig: 'group',
						propertiesOrder: [
							'heading',
							'subheading',
							'images',
							'call_to_action_text',
							'call_to_action_link',
						],
						of: {
							dataType: 'string',
							enumValues: [
								{
									id: '',
									label: '',
								},
							],
						},
					},
					bullet_stats_card: {
						keyValue: false,
						propertiesOrder: [
							'heading',
							'body_text',
							'image',
							'image_alt_text',
						],
						propertyConfig: 'group',
						editable: true,
						properties: {
							body_text: {
								editable: true,
								defaultValue: 'This is where body text will go. You can add bullet points in FireCMS Cloud UI.',
								dataType: 'string',
								propertyConfig: 'markdown',
								markdown: true,
								name: 'Body Text',
							},
							image_alt_text: {
								name: 'Image Alt Text',
								propertyConfig: 'text_field',
								editable: true,
								dataType: 'string',
							},
							heading: {
								propertyConfig: 'markdown',
								defaultValue: 'Heading Goes Here',
								editable: true,
								markdown: true,
								name: 'Heading',
								dataType: 'string',
							},
							image: {
								dataType: 'string',
								editable: true,
								storage: {
									acceptedFiles: [
										'image/*',
									],
									storagePath: '/',
									storeUrl: true,
								},
								name: 'Image',
								propertyConfig: 'file_upload',
							},
						},
						name: 'Bullet Stats Card',
						dataType: 'map',
					},
					card: {
						editable: true,
						propertyConfig: 'repeat',
						name: 'Card',
						of: {
							dataType: 'map',
							editable: true,
							properties: {
								heading: {
									markdown: true,
									dataType: 'string',
									name: 'Heading',
									propertyConfig: 'markdown',
									editable: true,
									defaultValue: 'Heading Goes Here',
								},
								alt_image_text: {
									editable: true,
									dataType: 'string',
									name: 'Alt Image Text',
									propertyConfig: 'text_field',
								},
								image: {
									dataType: 'array',
									propertyConfig: 'multi_file_upload',
									editable: true,
									name: 'Image',
									of: {
										dataType: 'string',
										storage: {
											storeUrl: true,
											storagePath: '/',
											acceptedFiles: [
												'image/*',
												'video/*',
											],
										},
									},
								},
								body_text: {
									dataType: 'string',
									editable: true,
									propertyConfig: 'markdown',
									defaultValue: 'Body text goes here. Remember, it is a card, so space is relatively limited.',
									name: 'Body Text',
									markdown: true,
								},
							},
							name: '',
							propertiesOrder: [
								'heading',
								'body_text',
								'image',
								'alt_image_text',
							],
							propertyConfig: 'group',
							keyValue: false,
						},
						dataType: 'array',
					},
					image: {
						of: {
							dataType: 'string',
							storage: {
								storeUrl: true,
								acceptedFiles: [
									'image/*',
									'video/*',
								],
								storagePath: '/',
							},
						},
						dataType: 'array',
						name: 'Image',
						validation: {
							required: false,
						},
						propertyConfig: 'multi_file_upload',
						editable: true,
					},
				},
			},
		},
		seo_metadata: {
			hideFromCollection: true,
			dataType: 'map',
			properties: {
				meta_title: {
					dataType: 'string',
					editable: true,
					name: 'Meta Title',
				},
				focus_keywords: {
					dataType: 'array',
					editable: true,
					name: 'Focus Keywords',
					of: {
						dataType: 'string',
					},
				},
				meta_description: {
					name: 'Meta Description',
					dataType: 'string',
					editable: true,
				},
			},
			name: 'SEO Metadata',
		},
		last_updated: {
			dataType: 'date',
			name: 'Last Updated',
			columnWidth: 237.20001220703125,
			autoValue: 'on_update',
		},
		is_published: {
			columnWidth: 242.20001220703125,
			description: 'Should this page be live on the site?',
			name: 'Is Published',
			dataType: 'boolean',
		},
	},
	subcollections: [],
}